// Generated by CoffeeScript 1.6.3
(function() {
  var $, fg;

  $ = jQuery;

  fg = friGame;

  $(function() {
    fg.resourceManager.addSound('stereomp3', 'news_intro.mp3').addSound('monomp3', 'prova.mp3').addSound('news', ['news_intro.ogg', 'news_intro.mp3']).addSound('prova', ['prova.ogg', 'prova.mp3']);
    return $('#start').one('click', function() {
      return fg.startGame(function() {
        var debug_print, k, v, _ref;
        $('<div id="loaded">Loaded</div>').insertBefore('#playground');
        $('<div id="dbgconsole"></div>').insertAfter('#loaded');
        debug_print = function(text) {
          return $('<div></div>').html(text).appendTo('#dbgconsole');
        };
        $('#loadmono').click(function() {
          fg.m.music.stop();
          if (fg.r.s_news) {
            fg.resourceManager.removeResource('s_news');
          }
          if (fg.r.s_prova) {
            fg.resourceManager.removeResource('s_prova');
          }
          fg.resourceManager.addSound('s_prova', ['prova.ogg', 'prova.mp3'], {
            streaming: true
          });
          return fg.startGame(function() {
            debug_print('Loaded mono');
            debug_print("audio: " + fg.r.s_prova.audio);
            if (fg.r.s_prova.audio) {
              debug_print("src: " + fg.r.s_prova.audio.src);
              debug_print("error: " + fg.r.s_prova.audio.error);
              debug_print("networkState: " + fg.r.s_prova.audio.networkState);
              return debug_print("readyState: " + fg.r.s_prova.audio.readyState);
            }
          });
        });
        $('#loadstereo').click(function() {
          fg.m.music.stop();
          if (fg.r.s_news) {
            fg.resourceManager.removeResource('s_news');
          }
          if (fg.r.s_prova) {
            fg.resourceManager.removeResource('s_prova');
          }
          fg.resourceManager.addSound('s_news', ['news_intro.ogg', 'news_intro.mp3'], {
            streaming: true
          });
          return fg.startGame(function() {
            debug_print('Loaded stereo');
            debug_print("audio: " + fg.r.s_news.audio);
            if (fg.r.s_news.audio) {
              debug_print("src: " + fg.r.s_news.audio.src);
              debug_print("error: " + fg.r.s_news.audio.error);
              debug_print("networkState: " + fg.r.s_news.audio.networkState);
              return debug_print("readyState: " + fg.r.s_news.audio.readyState);
            }
          });
        });
        debug_print('canPlay:');
        _ref = fg.m.canPlay;
        for (k in _ref) {
          v = _ref[k];
          debug_print("" + k + ": " + v);
        }
        debug_print("audioBuffer: " + fg.r.news.audioBuffer);
        fg.playground();
        fg.m.addMultiChannel('sfx');
        fg.m.addSingleChannel('music');
        $('#monomp3').click(function() {
          return fg.m.sfx.play('monomp3');
        });
        $('#stereomp3').click(function() {
          return fg.m.sfx.play('stereomp3');
        });
        $('#monosfx').click(function() {
          return fg.m.sfx.play('prova');
        });
        $('#stereosfx').click(function() {
          return fg.m.sfx.play('news');
        });
        $('#monowebaudio').click(function() {
          return fg.m.music.play('prova', {
            loop: true
          });
        });
        $('#stereowebaudio').click(function() {
          return fg.m.music.play('news', {
            loop: true
          });
        });
        $('#monohtml5').click(function() {
          fg.m.music.play('s_prova', {
            loop: true
          });
          if (fg.r.s_prova) {
            if (fg.r.s_prova.audio) {
              debug_print("src: " + fg.r.s_prova.audio.src);
              debug_print("error: " + fg.r.s_prova.audio.error);
              debug_print("networkState: " + fg.r.s_prova.audio.networkState);
              return debug_print("readyState: " + fg.r.s_prova.audio.readyState);
            }
          }
        });
        $('#stereohtml5').click(function() {
          fg.m.music.play('s_news', {
            loop: true
          });
          if (fg.r.s_news) {
            if (fg.r.s_news.audio) {
              debug_print("src: " + fg.r.s_news.audio.src);
              debug_print("error: " + fg.r.s_news.audio.error);
              debug_print("networkState: " + fg.r.s_news.audio.networkState);
              return debug_print("readyState: " + fg.r.s_news.audio.readyState);
            }
          }
        });
        $('#panleft').click(function() {
          fg.m.sfx.tween({
            panning: -1
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: -1
          }, {
            duration: 1000
          });
        });
        $('#pancenter').click(function() {
          fg.m.sfx.tween({
            panning: 0
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: 0
          }, {
            duration: 1000
          });
        });
        $('#panright').click(function() {
          fg.m.sfx.tween({
            panning: 1
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: 1
          }, {
            duration: 1000
          });
        });
        return $('#stop').click(function() {
          return fg.m.music.stop();
        });
      });
    });
  });

}).call(this);
