// Generated by CoffeeScript 1.6.3
(function() {
  var $, fg;

  $ = jQuery;

  fg = friGame;

  $(function() {
    fg.resourceManager.addSound('news', 'news_intro.ogg').addSound('prova', 'prova.ogg').addSound('s_news', 'news_intro.ogg', {
      streaming: true
    }).addSound('s_prova', 'prova.ogg', {
      streaming: true
    });
    return fg.startGame(function() {
      fg.playground();
      fg.m.addMultiChannel('sfx');
      fg.m.addSingleChannel('music');
      $('#monosfx').click(function() {
        return fg.m.sfx.play({
          sound: 'prova'
        });
      });
      $('#stereosfx').click(function() {
        return fg.m.sfx.play({
          sound: 'news'
        });
      });
      $('#monowebaudio').click(function() {
        return fg.m.music.play({
          sound: 'prova',
          loop: true
        });
      });
      $('#stereowebaudio').click(function() {
        return fg.m.music.play({
          sound: 'news',
          loop: true
        });
      });
      $('#monohtml5').click(function() {
        return fg.m.music.play({
          sound: 's_prova',
          loop: true
        });
      });
      $('#stereohtml5').click(function() {
        return fg.m.music.play({
          sound: 's_news',
          loop: true
        });
      });
      $('#panleft').click(function() {
        fg.m.sfx.tween({
          panning: -1
        }, {
          duration: 1000
        });
        return fg.m.music.tween({
          panning: -1
        }, {
          duration: 1000
        });
      });
      $('#pancenter').click(function() {
        fg.m.sfx.tween({
          panning: 0
        }, {
          duration: 1000
        });
        return fg.m.music.tween({
          panning: 0
        }, {
          duration: 1000
        });
      });
      $('#panright').click(function() {
        fg.m.sfx.tween({
          panning: 1
        }, {
          duration: 1000
        });
        return fg.m.music.tween({
          panning: 1
        }, {
          duration: 1000
        });
      });
      return $('#stop').click(function() {
        return fg.m.music.stop();
      });
    });
  });

}).call(this);
