// Generated by CoffeeScript 1.6.3
(function() {
  var $, fg;

  $ = jQuery;

  fg = friGame;

  $(function() {
    fg.resourceManager.addSound('stereomp3', 'news_intro.mp3').addSound('monomp3', 'prova.mp3').addSound('news', ['news_intro.ogg', 'news_intro.mp3']).addSound('prova', ['prova.ogg', 'prova.mp3']).addSound('s_news', ['news_intro.ogg', 'news_intro.mp3'], {
      streaming: true
    }).addSound('s_prova', ['prova.ogg', 'prova.mp3'], {
      streaming: true
    });
    return $('#start').one('click', function() {
      return fg.startGame(function() {
        $('<div>Loaded</div>').prependTo('#playground');
        fg.playground();
        fg.m.addMultiChannel('sfx');
        fg.m.addSingleChannel('music');
        $('#monomp3').click(function() {
          return fg.m.sfx.play('monomp3');
        });
        $('#stereomp3').click(function() {
          return fg.m.sfx.play('stereomp3');
        });
        $('#monosfx').click(function() {
          return fg.m.sfx.play('prova');
        });
        $('#stereosfx').click(function() {
          return fg.m.sfx.play('news');
        });
        $('#monowebaudio').click(function() {
          return fg.m.music.play('prova', {
            loop: true
          });
        });
        $('#stereowebaudio').click(function() {
          return fg.m.music.play('news', {
            loop: true
          });
        });
        $('#monohtml5').click(function() {
          return fg.m.music.play('s_prova', {
            loop: true
          });
        });
        $('#stereohtml5').click(function() {
          return fg.m.music.play('s_news', {
            loop: true
          });
        });
        $('#panleft').click(function() {
          fg.m.sfx.tween({
            panning: -1
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: -1
          }, {
            duration: 1000
          });
        });
        $('#pancenter').click(function() {
          fg.m.sfx.tween({
            panning: 0
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: 0
          }, {
            duration: 1000
          });
        });
        $('#panright').click(function() {
          fg.m.sfx.tween({
            panning: 1
          }, {
            duration: 1000
          });
          return fg.m.music.tween({
            panning: 1
          }, {
            duration: 1000
          });
        });
        return $('#stop').click(function() {
          return fg.m.music.stop();
        });
      });
    });
  });

}).call(this);
